language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx
dist: trusty

notifications:
  email:
    recipients:
      - falconn.lib@gmail.com
    on_success: never
    on_failure: always

install:
  - make python_package
  - cd python_pkg/dist/FALCONN-* && pip install .

script:
  - make run_all_cpp_tests
  - make run_all_python_tests
